baseURL = "https://pwntus.github.io/mic-workshops/"
languageCode = "en-us"
title = "Managed IoT Cloud Workshops"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
publishDir="../public"

[params]
  # General information
  author = "Pontus Edvard Aurdal"
  description = "Easy to follow, step-by-step tutorials for the Telenor Managed IoT Cloud platform."
  copyright = ""

  # Repository
  provider = ""
  repo_url = ""

  version = ""
  logo = "images/logo.png"
  favicon = "images/favicon.ico"

  permalink = "#"

  # Custom assets
  custom_css = ["stylesheets/custom.css"]
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  [params.palette]
      primary = "#47abe2"
      accent  = "#af3269"

    [params.font]
      text = "Ubuntu"
      code = "Ubuntu Mono"


[social]
  twitter = ""
  github  = "pwntus"
  repo    = "pwntus/mic-workshops"
  email   = "pontus.edvard@gmail.com"


[[menu.main]]
  name   = "Getting Started"
  url    = "getting-started/"
  weight = 100

[[menu.main]]
  name   = "Workshop 1: Creating a API Client"
  url    = "workshop-1/"
  weight = 200

[[menu.main]]
  name   = "Workshop 2: Using the API"
  url    = "workshop-2/"
  weight = 300

[[menu.main]]
  name   = "Workshop 3: Vue.js"
  url    = "workshop-3/"
  weight = 400


[blackfriday]
  smartypants = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
